ingress:
  enabled: true
  hostname: auth.pr-mac.com
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls: true

postgresql:
  enabled: false
externalDatabase:
  host: postgres.pr-mac.com
  user: postgres
  password: ${postgres_password}
  database: keycloak
  port: 5432

auth:
  adminUser: admin
  adminPassword: admin
  tls:
    termination: edge
