ingress:
  enabled: true
  certManager: true
  hostname: auth.pr-mac.com
  ingressClassName: nginx
  tls:
    enabled: true
    secretName: auth-cert
postgresql:
  enabled: false
externalDatabase:
  host: "none"
extraEnvVars:
  - name: KEYCLOAK_DATABASE_VENDOR
    value: "dev-file"