ingress:
  enabled: true
  hostname: auth.pr-mac.com
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls: true
postgresql:
  enabled: false
externalDatabase:
  host: "none"
extraEnvVars:
  - name: KEYCLOAK_DATABASE_VENDOR
    value: "dev-file"
extraVolumes:
  - name: kc-ps
    persistentVolumeClaim:
      claimName: k8s-pvc
extraVolumeMounts:
  - name: kc-ps
    mountPath: /opt/jboss/keycloak/data

auth:
  adminUser: admin
  adminPassword: admin
  tls:
    termination: edge
