ingress:
  enabled: true
  certManager: true
  hostname: auth.pr-mac.com
  ingressClassName: nginx
  tls: true
postgresql:
  enabled: false
externalDatabase:
  host: "none"
extraEnvVars:
  - name: KEYCLOAK_DATABASE_VENDOR
    value: "dev-file"