ingress:
  enabled: true
  certManager: true
  hostname: auth.pr-mac.com
  ingressClassName: nginx
  annotations:
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt
  tls: true
postgresql:
  enabled: false
externalDatabase:
  host: "none"
extraEnvVars:
  - name: KEYCLOAK_DATABASE_VENDOR
    value: "dev-file"