#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: rest-service-cert
#  namespace: prm
#spec:
#  secretName: rest-service-cert
#  issuerRef:
#    name: letsencrypt-staging
#    kind: ClusterIssuer
#  dnsNames:
#    - rest-service.pr-mac.com
#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: auth-cert
#  namespace: prm
#spec:
#  secretName: auth-cert
#  issuerRef:
#    name: letsencrypt-staging
#    kind: ClusterIssuer
#  dnsNames:
#    - auth.pr-mac.com

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-service-cert
  namespace: prm
spec:
  secretName: postgres-service-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - postgres-service.pr-mac.com