apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rest-service-cert
  namespace: prm
spec:
  secretName: rest-service-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - rest-service.pr-mac.com
