name: Azure Deploy
description: Deploy to Azure Helm

inputs:
  project:
    description: The project to deploy
    required: true
  version:
    description: The version of the service to deploy
    required: true
  client_id:
    description: The client_id
    required: true
  client_secret:
    description: The client_secret
    required: true
  subscription_id:
    description: The subscription_id
    required: true
  tenant_id:
    description: The tenant_id
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Authenticate
      uses: ./.github/actions/azure-auth
      with:
        client_id: ${{inputs.client_id}}
        tenant_id: ${{inputs.tenant_id}}
        subscription_id: ${{inputs.subscription_id}}
        azure_credentials: ${{inputs.azure_credentials}}
    - name: Deploy
      shell: bash
      run: |
        yq -i ".appVersion = \"${{ inputs.version }}\"" "projects/${{ inputs.project }}/deploy/Chart.yaml"

        echo '::group::Install Helm dependencies'
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install helm
        helm dependency update "projects/${{ inputs.project }}/deploy"
        echo '::endgroup::'

        set +o pipefail
        for attempt in $(seq 1 $MAX_ATTEMPTS); do
          echo "::group::Helm upgrade (attempt $attempt)"
          exec helm upgrade '${{ inputs.project }}' 'projects/${{ inputs.project }}/deploy' \
            --atomic \
            --history-max 10 \
            --force \
            --install \
            --reset-values \
            --set 'version=${{ inputs.version }}' \
            --set 'generic-service.image.tag=${{ inputs.version }}' \
            --set 'generic-service.env.VERSION=${{ inputs.version }}' \
            --set "generic-service.env.BUILD_INFO=$([ -r "$BUILD_INFO" ] && cat "$BUILD_INFO" | base64 -w0 || echo)" \
            --set "generic-service.env.GIT_INFO=$([ -r "$GIT_INFO" ] && cat "$GIT_INFO" | base64 -w0 || echo)" \
            --timeout 10m \
            --values templates/helm-defaults.yml \
            --values 'projects/${{ inputs.project }}/deploy/values.yaml' \
            --values 'projects/${{ inputs.project }}/deploy/${{ steps.env.outputs.values-file }}' \
            --wait 2>&1 | tee "helm-$attempt.log"
          exit_code=${PIPESTATUS[0]}
          echo "Exit code: $exit_code" 
          echo '::endgroup::'
        
          # Retry Helm upgrade if we get a timeout error from Azure K8s
          if [ $exit_code -eq 1 ] && grep -q timeout "helm-$attempt.log"; then continue; else exit $exit_code; fi
        done
        if [ $exit_code -ne 0 ]; then exit $exit_code; fi
      env:
        BUILD_INFO: projects/${{ inputs.project }}/build-info.properties
        GIT_INFO: projects/${{ inputs.project }}/git.properties
        MAX_ATTEMPTS: '3'