# Default config
server.shutdown: graceful
spring:
  jackson:
    default-property-inclusion: non_null
  threads.virtual.enabled: true
  datasource.url: jdbc:h2:file:./dev;MODE=PostgreSQL;DEFAULT_NULL_ORDERING=HIGH;AUTO_SERVER=true;AUTO_SERVER_PORT=9092
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints.web:
    base-path: /
    exposure.include: [ "health", "info" ]
  endpoint.health.show-details: always

---
# dev/test config
spring.config.activate.on-profile: [ "dev", "integration-test" ]
server.shutdown: immediate

logging.level:
  com.prm: DEBUG
  org.hibernate.tool.schema: ERROR
  org.apache.activemq: WARN
