
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: $SERVICE_NAME-cert
  namespace: prm
spec:
  secretName: $SERVICE_NAME-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - $SERVICE_SHORT_URL
    - $SERVICE_URL
