# Common values
enabled: true

generic-service:
  nameOverride: rest-service

  image:
    repository: ghcr.io/pmcphee77/rest-service

  ingress:
    className: nginx
    tlsSecretName: rest-service-cert

  imagePullSecrets:
    - name: regcred

