name: "Azure Login Workflow"

on:
  push:
    branches:
      - main

jobs:
  SetUpTerraform:
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false      
      - name: Terraform init
        working-directory: ./.github
        run: terraform init
  TerraformPlan:
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
      reviewers: 'pmcphee77'
      GH_TOKEN: ${{ steps.app-token.outputs.token }}
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Plan
        working-directory: ./.github
        run: terraform plan -out "tfplan"
