name: "Azure Login Workflow"

on:
  push:
    branches:
      - main

jobs:
  azureLogin:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
