name: "Destroy K8s Cluster"

on:
  workflow_dispatch:

jobs:
  TerraformDestroy:
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_docker_password: ${{ secrets.GHCR_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false      
      - name: Terraform init
        working-directory: ./infrastructure
        run: terraform init -lock=false
      - name: Terraform Destroy
        working-directory: ./infrastructure
        run: terraform destroy -auto-approve -lock=false
